### ISSUE TITLE
upgrade pixelmatch

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-test-suite#53]
I reverted 514c45cb2dd5953d383151e0362485f0454a7314 and bfedd3dfed7bf7cf6afa3c6aa97c58ed0b6ffb67 because they require going through and adjusting thresholds and ignores for both mapbox-gl-js and mapbox-gl-native, and I don't have the time ATM.

When someone does have the time, we can do that and revert the revert.

cc @mourner

**Comment by mourner** [comment]
@jfirebaugh sounds good! Note that we need to adjust the thresholds _again_ because of https://github.com/mapbox/pixelmatch/releases/tag/v4.0.0 :)

**Comment by mourner** [comment]
I have spent some time on this in the `pixelmatch4` branch. Basically, as the algorithm got more precise and sensitive where previously it would forgive a lot of errors by falsely detecting them as antialiasing, it now fails a lot more. 

So we need to either set the ignored flag on a lot more tests, or significantly increase diff thresholds (how many diff pixels are considered a fail vs pass) or pixelmatch threshold (what perceptual color distance will count a pixel as "different") to give us a false impression of nicely passing tests. 

The disadvantage of the first (beside the discomfort) would be that ignored tests will not fail the build even if the diff is significantly bigger than the expected small diff due to rendering differences. 

The disadvantage of the second is that valid errors may go unnoticed (e.g. if a single icon is heavily displaced, it will still may fall under threshold because there are not many pixels involved, as opposed to very minor antialiasing difference that triggers a lot of different pixels with a sensitive threshold).

I would probably prefer the first (go as sensitive as possible and switch ignore for a lot of tests), but not sure.

**Comment by jfirebaugh** [comment]
Ignoring tests means they effectively _never_ fail, same as if you set the threshold to infinity. So it's strictly less coverage than the second, right?

**Comment by mourner** [comment]
@jfirebaugh they never fail but at least indicate "there's a problem here", as opposed to upping the diff, then forgetting why it was like this. Maybe instead of just putting `ignore`, we should introduce a second diff value for it, and then still fail the test if it's higher than the ignore diff, silently show as yellow ("passes with issues") if it goes beyond the default diff, and then pass normally if it doesn't.

**Comment by jfirebaugh** [comment]
Done in f55aafc460f506873e72a1f44d5b96dfe5869a0b and followup commits. Rather than adjust a lot of thresholds, I rewrote many of the tests to be simpler, more targeted to their specific property and only that property, and less susceptible to GPU/driver differences.

**Comment by mourner** [comment]
@jfirebaugh fantastic! Did you notice the difference in anti-aliasing detection?
